/*
 * Type Definitions for CUDA Hashing Algos
 *
 * Date: 12 June 2019
 * Revision: 1
 *
 * This file is released into the Public Domain.
 */

#ifndef CONFIG_H
#define CONFIG_H

#define USE_MD5 1
#define USE_SHA256 1
#define SHA256_BLOCK_SIZE 32            // SHA256 outputs a 32 byte digest

#define MAX_PASSWORD_LENGTH 8
//#define LEGAL_CHARS "\0abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*"
#define LEGAL_CHARS "\0abcdefghijklmnopqrstuvwxyz"
#define NUM_LEGAL_CHARS 27L

__constant__ long CARTESIAN_PRODUCT_DENOMINATORS[] = {
    1,
    NUM_LEGAL_CHARS,
    NUM_LEGAL_CHARS*NUM_LEGAL_CHARS,
    NUM_LEGAL_CHARS*NUM_LEGAL_CHARS*NUM_LEGAL_CHARS,
    NUM_LEGAL_CHARS*NUM_LEGAL_CHARS*NUM_LEGAL_CHARS*NUM_LEGAL_CHARS,
    NUM_LEGAL_CHARS*NUM_LEGAL_CHARS*NUM_LEGAL_CHARS*NUM_LEGAL_CHARS*NUM_LEGAL_CHARS,
    NUM_LEGAL_CHARS*NUM_LEGAL_CHARS*NUM_LEGAL_CHARS*NUM_LEGAL_CHARS*NUM_LEGAL_CHARS*NUM_LEGAL_CHARS,
    NUM_LEGAL_CHARS*NUM_LEGAL_CHARS*NUM_LEGAL_CHARS*NUM_LEGAL_CHARS*NUM_LEGAL_CHARS*NUM_LEGAL_CHARS*NUM_LEGAL_CHARS,
	NUM_LEGAL_CHARS*NUM_LEGAL_CHARS*NUM_LEGAL_CHARS*NUM_LEGAL_CHARS*NUM_LEGAL_CHARS*NUM_LEGAL_CHARS*NUM_LEGAL_CHARS*NUM_LEGAL_CHARS,
};
#define NUM_PASSWORDS (NUM_LEGAL_CHARS*NUM_LEGAL_CHARS*NUM_LEGAL_CHARS*NUM_LEGAL_CHARS*NUM_LEGAL_CHARS*NUM_LEGAL_CHARS*NUM_LEGAL_CHARS*NUM_LEGAL_CHARS)
#define THREADS_PER_BLOCK 1024L
#define PASSWORDS_PER_THREAD 512L


typedef unsigned char BYTE;
typedef unsigned int  WORD;
typedef unsigned long long LONG;

#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#endif